name: CI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Free space:"
          df -h
      - name: Creating TWRP directory
        run: |
          mkdir TWRP
          cd TWRP
          sudo apt install repo -y
          git config --global user.name "OPTIMALGLADIUS"
          git config --global user.email "${{ secrets.EMAIL }}"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
          repo sync
          git clone https://github.com/OPTIMALGLADIUS/android_lenovo-tb-8506X.git device/lenovo/tb8506x
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
